name: Publicar Post Aleatorio

on:
  schedule:
    - cron: '0 9 * * *'  # Ejecuta a las 9 AM UTC todos los días
  workflow_dispatch:      # Permite ejecución manual

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias
        run: pip install requests
      
      - name: Ejecutar Bot
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
